version: 0.2
  # - name: Build and push Docker images
  #   uses: docker/build-push-action@v2.6.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 602955111154.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t mongodb-s3:latest .
      - docker tag mongodb-s3:latest 602955111154.dkr.ecr.us-east-2.amazonaws.com/mongodb-s3:1.1.5
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 602955111154.dkr.ecr.us-east-2.amazonaws.com/mongodb-s3:1.1.5
