name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mongodb-s3:$(date +%s)
    - name: tag docker image
      run: docker tag mongodb-s3:$(date +%s) rightsaidfred/mongodb-s3:latest
    - name: Push Docker image  
      run: docker push rightsaidfred/mongodb-s3:latest
